name: Secure Portfolio Deployment

on:
  push:
    branches: [ main ]

permissions:
  id-token: write # Required for the OIDC "handshake"
  contents: read  # Required to read your code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1' # This tells the pipeline to FAIL if a security risk is found
          severity: 'CRITICAL,HIGH'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 sync . s3://beginner-devops-portfolio-2026 --exclude ".git/*" --exclude ".github/*" --exclude "*.tf*" --exclude ".terraform*"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Build Docker Image
        run: |
          docker build -t my-security-api:${{ github.sha }} .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-security-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Fail the build if vulnerabilities are found
          severity: 'CRITICAL,HIGH'